openapi: 3.0.0
info:
  title: Berkeley Covid-19 Risk API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.0.1
servers:
  - url: http://covidrisk.berkeley.edu/v1
    description: Production API
  - url: http://test-covidrisk.berkeley.edu/v1
    description: Testing server
paths:
  /risk/query:
    post:
      summary: Returns a list of .
      description: Optional extended description in CommonMark or HTML.
      requestBody:
        content:
          application/json:
            schema: # Request body contents
              type: array
              items:
                type: object
                properties:
                  latitude:
                    type: number
                    description: Latitude
                  longitude:
                    type: number
                  time:
                    type: string
                    format: date-time
                example:   # Sample object
                  latitude: 37.871937
                  longitude: -122.258562
                  time: "2020-03-27T06:10:42+00:00"
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
        '400':
          description: "Invalid query value"
  /risk/publish:
    post:
      summary: Updates the database of Covid-19 exposure
      
      responses:
        '200':
          description: Successful update
        '400':
          description: Update failed